### PR TITLE
Update `tone_to_plain` mapping

### PR DESCRIPTION
**Pull request by leiless**
As I investigate through the [mozillazg/pinyin-data/pinyin.txt](https://github.com/mozillazg/pinyin-data/blob/master/pinyin.txt), I found some tones are missing from the `tone_to_plain` map.

# Verification:

<details>
<summary>You need to compile the <code>Main.java</code></summary>

```java
import java.io.IOException;
import java.lang.management.ManagementFactory;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.Normalizer;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.TreeMap;
import java.util.TreeSet;

public class Main {
    private static boolean isComposedForm(String s) {
        return Normalizer.isNormalized(s, Normalizer.Form.NFC);
    }

    private static boolean isDecomposedForm(String s) {
        return Normalizer.isNormalized(s, Normalizer.Form.NFD);
    }

    @SuppressWarnings("BooleanMethodIsAlwaysInverted")
    private static boolean isNormalForm(String s) {
        return isComposedForm(s) && isDecomposedForm(s);
    }

    private static String toDecomposedForm(String s) {
        return Normalizer.normalize(s, Normalizer.Form.NFD);
    }

    private static boolean isAsciiChar(char c) {
        return StandardCharsets.US_ASCII.newEncoder().canEncode(c);
    }

    public static void main(String[] args) throws IOException {
        // https://stackoverflow.com/questions/13029915/how-to-programmatically-test-if-assertions-are-enabled
        boolean assertionsEnabled = ManagementFactory.getRuntimeMXBean().getInputArguments().contains("-ea");
        if (!assertionsEnabled) {
            throw new RuntimeException("-ea JVM argument must be specified");
        }

        if (args.length != 1) {
            throw new IllegalArgumentException("Usage: this pinyin.txt");
        }

        Path path = Paths.get(args[0]);
        List<String> allLines = Files.readAllLines(path);

        Set<String> pinyinSet = new TreeSet<>();
        Map<String, Character> tuneMap = new TreeMap<>();

        for (String s : allLines) {
            if (!isNormalForm(s)) {
                for (int i = 0; i < s.length(); i++) {
                    String c = "" + s.charAt(i);
                    // The pinyin.txt uses NFC for toned characters
                    // We must assure this so we can properly handle all of them
                    assert isComposedForm(c);

                    if (!isNormalForm(c)) {
                        String nfd = toDecomposedForm(c);
                        assert c.length() < nfd.length();
                        assert isAsciiChar(nfd.charAt(0));
                        for (int j = 1; j < nfd.length(); j++) {
                            assert !isAsciiChar(nfd.charAt(j));
                        }

                        Character old = tuneMap.putIfAbsent(c, nfd.charAt(0));
                        assert old == null || old.equals(nfd.charAt(0));

                        s = s.replace(c, "" + nfd.charAt(0));
                        // Reconsume this character
                        i--;
                    }
                }
            }

            pinyinSet.add(s);
        }

        System.out.println(pinyinSet.size());
        for (String s : pinyinSet) {
            System.out.println(s);
        }

        System.out.println();
        System.out.println(tuneMap.size());
        for (Map.Entry<String, Character> kv : tuneMap.entrySet()) {
            System.out.println(kv.getKey() + ",'" + kv.getValue() + "'");
        }
    }
}
```
</details>  

```bash
cat contrib/pinyin.txt | cut -d'#' -f1 | cut -d':' -f2 |  tr ',' '\n' | awk '{print $1}' | sort -u | grep -Ev "^(\s+)?$" > all_pinyin.txt
javac Main.java
java -ea Main all_pinyin.txt
```

## Q: why use Java for investigation?
Java has built-in Unicode support which I'm familiar with.

# Output

<details>
<summary>Click to see...</summary>

```
426
a
ai
an
ang
ao
ba
bai
ban
bang
bao
bei
ben
beng
bi
bian
biang
biao
bie
bin
bing
bo
bu
ca
cai
can
cang
cao
ce
cei
cen
ceng
cha
chai
chan
chang
chao
che
chen
cheng
chi
chong
chou
chu
chua
chuai
chuan
chuang
chui
chun
chuo
ci
cong
cou
cu
cuan
cui
cun
cuo
da
dai
dan
dang
dao
de
dei
den
deng
di
dia
dian
diao
die
din
ding
diu
dong
dou
du
duan
dui
dun
duo
e
ei
en
eng
er
ē
ě
fa
fan
fang
fei
fen
feng
fiao
fo
fou
fu
ga
gai
gan
gang
gao
ge
gei
gen
geng
gong
gou
gu
gua
guai
guan
guang
gui
gun
guo
ha
hai
han
hang
hao
he
hei
hen
heng
hm
hng
hong
hou
hu
hua
huai
huan
huang
hui
hun
huo
ji
jia
jian
jiang
jiao
jie
jin
jing
jiong
jiu
ju
juan
jue
jun
ka
kai
kan
kang
kao
ke
kei
ken
keng
kong
kou
ku
kua
kuai
kuan
kuang
kui
kun
kuo
la
lai
lan
lang
lao
le
lei
len
leng
li
lia
lian
liang
liao
lie
lin
ling
liu
lo
long
lou
lu
luan
lue
lun
luo
m
ma
mai
man
mang
mao
me
mei
men
meng
mi
mian
miao
mie
min
ming
miu
mo
mou
mu
m̀
m̄
n
na
nai
nan
nang
nao
ne
nei
nen
neng
ng
ni
nia
nian
niang
niao
nie
nin
ning
niu
nong
nou
nu
nuan
nue
nun
nuo
o
ou
pa
pai
pan
pang
pao
pei
pen
peng
pi
pian
piao
pie
pin
ping
po
pou
pu
qi
qia
qian
qiang
qiao
qie
qin
qing
qiong
qiu
qu
quan
que
qun
ran
rang
rao
re
ren
reng
ri
rong
rou
ru
rua
ruan
rui
run
ruo
sa
sai
san
sang
sao
se
sen
seng
sha
shai
shan
shang
shao
she
shei
shen
sheng
shi
shou
shu
shua
shuai
shuan
shuang
shui
shun
shuo
si
song
sou
su
suan
sui
sun
suo
ta
tai
tan
tang
tao
te
tei
teng
ti
tian
tiao
tie
ting
tong
tou
tu
tuan
tui
tun
tuo
wa
wai
wan
wang
wei
wen
weng
wo
wong
wu
xi
xia
xian
xiang
xiao
xie
xin
xing
xiong
xiu
xu
xuan
xue
xun
ya
yan
yang
yao
ye
yi
yin
ying
yo
yong
you
yu
yuan
yue
yun
za
zai
zan
zang
zao
ze
zei
zen
zeng
zha
zhai
zhan
zhang
zhao
zhe
zhei
zhen
zheng
zhi
zhong
zhou
zhu
zhua
zhuai
zhuan
zhuang
zhui
zhun
zhuo
zi
zong
zou
zu
zuan
zui
zun
zuo

31
à,'a'
á,'a'
è,'e'
é,'e'
ê,'e'
ì,'i'
í,'i'
ò,'o'
ó,'o'
ù,'u'
ú,'u'
ü,'u'
ā,'a'
ē,'e'
ě,'e'
ī,'i'
ń,'n'
ň,'n'
ō,'o'
ū,'u'
ǎ,'a'
ǐ,'i'
ǒ,'o'
ǔ,'u'
ǘ,'u'
ǚ,'u'
ǜ,'u'
ǹ,'n'
ḿ,'m'
ế,'e'
ề,'e'
```
</details>

After I compared with existing data in`pinyin.h`, and I found `ê`, `ü` is missing.
```diff
diff --git a/10 b/11
index 15b8490..a4a2895 100644
--- a/10
+++ b/11
@@ -4,6 +4,7 @@
 ā,'a'
 é,'e'
 è,'e'
+ê,'e'
 ế,'e'
 ề,'e'
 ě,'e'
@@ -23,6 +24,7 @@
 ú,'u'
 ù,'u'
 ǔ,'u'
+ü,'u'
 ǘ,'u'
 ǜ,'u'
 ǚ,'u'
```

`10`: Existing data in `tone_to_plain`
`11`: Data extracted from `all_pinyin.txt`

### CODE REVIEW

**Comment by leiless** [comment]
What makes it more interesting is that `pinyin_prefix` and `pinyin_valid` also missing some pinyin "words".

<details>
<summary>Click to expand git diff result...</summary>
<p>

```diff
diff --git a/1 b/2
index 6a49150..ae15ceb 100644
--- a/1
+++ b/2
@@ -13,6 +13,7 @@ ben
 beng
 bi
 bian
+biang
 biao
 bie
 bin
@@ -25,6 +26,8 @@ can
 cang
 cao
 ce
+cei
+cen
 ceng
 cha
 chai
@@ -38,6 +41,7 @@ chi
 chong
 chou
 chu
+chua
 chuai
 chuan
 chuang
@@ -58,11 +62,15 @@ dan
 dang
 dao
 de
+dei
+den
 deng
 di
+dia
 dian
 diao
 die
+din
 ding
 diu
 dong
@@ -72,24 +80,30 @@ duan
 dui
 dun
 duo
-dia
 e
+ei
 en
+eng
 er
+ē
+ě
 fa
 fan
 fang
 fei
 fen
 feng
-fu
+fiao
+fo
 fou
+fu
 ga
 gai
 gan
 gang
 gao
 ge
+gei
 gen
 geng
 gong
@@ -111,6 +125,8 @@ he
 hei
 hen
 heng
+hm
+hng
 hong
 hou
 hu
@@ -125,7 +141,6 @@ ji
 jia
 jian
 jiang
-qiao
 jiao
 jie
 jin
@@ -136,13 +151,13 @@ ju
 juan
 jue
 jun
-jv
 ka
 kai
 kan
 kang
 kao
 ke
+kei
 ken
 keng
 kong
@@ -162,6 +177,7 @@ lang
 lao
 le
 lei
+len
 leng
 li
 lia
@@ -172,6 +188,7 @@ lie
 lin
 ling
 liu
+lo
 long
 lou
 lu
@@ -179,7 +196,7 @@ luan
 lue
 lun
 luo
-lv
+m
 ma
 mai
 man
@@ -199,6 +216,9 @@ miu
 mo
 mou
 mu
+m̀
+m̄
+n
 na
 nai
 nan
@@ -208,7 +228,9 @@ ne
 nei
 nen
 neng
+ng
 ni
+nia
 nian
 niang
 niao
@@ -217,11 +239,12 @@ nin
 ning
 niu
 nong
+nou
 nu
 nuan
 nue
+nun
 nuo
-nv
 o
 ou
 pa
@@ -245,6 +268,7 @@ qi
 qia
 qian
 qiang
+qiao
 qie
 qin
 qing
@@ -254,7 +278,6 @@ qu
 quan
 que
 qun
-qv
 ran
 rang
 rao
@@ -265,6 +288,7 @@ ri
 rong
 rou
 ru
+rua
 ruan
 rui
 run
@@ -283,6 +307,7 @@ shan
 shang
 shao
 she
+shei
 shen
 sheng
 shi
@@ -309,6 +334,7 @@ tan
 tang
 tao
 te
+tei
 teng
 ti
 tian
@@ -330,6 +356,7 @@ wei
 wen
 weng
 wo
+wong
 wu
 xi
 xia
@@ -345,7 +372,6 @@ xu
 xuan
 xue
 xun
-xv
 ya
 yan
 yang
@@ -376,6 +402,7 @@ zhan
 zhang
 zhao
 zhe
+zhei
 zhen
 zheng
 zhi
```
</details>

`1`: Existing data extracted from `pinyin_valid`
`2`: Data extracted from `all_pinyin.txt`

For instance, `cen`(参), `dei`(得), `den`(扥), `ei`(诶), `fo`(佛), `gei`(给), `lo`(咯), `tei`(忒) are all valid pinyins.
Yet they're missing from `pinyin_valid`.

Also, `pinyin_prefix` containing valid pinyin, e.g. `cen`, `den`, `fo`, `lo`.
Yet the comment `// 不是合法拼音，但是是前缀，只能出现在结尾·` is misleading?

Since the above analysis needs further confirmation, so I don't touch the `pinyin_prefix` and `pinyin_valid` part code.

**Comment by leiless** [comment]
> As I investigate through the [mozillazg/pinyin-data/pinyin.txt](https://github.com/mozillazg/pinyin-data/blob/master/pinyin.txt), I found some tones are missing from the `tone_to_plain` map.
> 
> # Verification:
> You need to compile the `Main.java`
> ```shell
> cat contrib/pinyin.txt | cut -d'#' -f1 | cut -d':' -f2 |  tr ',' '\n' | awk '{print $1}' | sort -u | grep -Ev "^(\s+)?$" > all_pinyin.txt
> javac Main.java
> java -ea Main all_pinyin.txt
> ```
> 
> ## Q: why use Java for investigation?
> Java has built-in Unicode support which I'm familiar with.
> 
> # Output
> ...

```
$ cat all_pinyin.txt | grep ê
ê̌
ê̄

$ cat all_pinyin.txt | grep ü
lüè
lüě
nüè
```

**Comment by wangfenjin** [comment]
> What makes it more interesting is that `pinyin_prefix` and `pinyin_valid` also missing some pinyin "words".
> Click to expand git diff result...
> 
> `1`: Existing data extracted from `pinyin_valid`
> `2`: Data extracted from `all_pinyin.txt`
> 
> For instance, `cen`(参), `dei`(得), `den`(扥), `ei`(诶), `fo`(佛), `gei`(给), `lo`(咯), `tei`(忒) are all valid pinyins.
> Yet they're missing from `pinyin_valid`.
> 
> Also, `pinyin_prefix` containing valid pinyin, e.g. `cen`, `den`, `fo`, `lo`.
> Yet the comment `// 不是合法拼音，但是是前缀，只能出现在结尾·` is misleading?
> 
> Since the above analysis needs further confirmation, so I don't touch the `pinyin_prefix` and `pinyin_valid` part code.

Hi @leiless , that's great! could you make a commit about this? thanks!

**Comment by leiless** [comment]
@wangfenjin, I found several other rarely used pinyin-s.

`eng` 鞥, `kei` 尅; 剋, `nou` 耨, `nun` 黁, `shei` 谁。
Should we add those or what?

The `shei` may add to the `pinyin_valid` since it's an informal form of 谁(`shui`).
see: [谁（中国汉字）_百度百科](https://baike.baidu.com/item/%E8%B0%81/2997)

**Comment by wangfenjin** [comment]
sure, let’s add them. thanks!

**Comment by wangfenjin** [comment]
thanks!

**Pull request merged**
